name: CI

"on": [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo_flags:
          - ""
          - "--no-default-features"
          - "--no-default-features --features \"serde\""
          - "--no-default-features --features \"serde-alloc\""
          - "--no-default-features --features \"serde-std\""
          - "--all-features"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all ${{ matrix.cargo_flags }} -- -D warnings

      - name: Run cargo clippy for tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests ${{ matrix.cargo_flags }} -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - toolchain: 1.46.0
            cargo_build_flags: ""
          - toolchain: stable
            cargo_build_flags: ""
          - toolchain: beta
            cargo_build_flags: ""
          - toolchain: nightly
            cargo_build_flags: "-Z features=dev_dep"
        cargo_flags:
          - ""
          - "--no-default-features"
          - "--no-default-features --features \"serde\""
          - "--no-default-features --features \"serde-alloc\""
          - "--no-default-features --features \"serde-std\""
          - "--no-default-features --features \"std serde\""
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.config.toolchain }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        continue-on-error: ${{ matrix.config.toolchain == 'nightly' }}
        with:
          command: build
          args: >-
            --verbose --all ${{ matrix.cargo_flags }}
            ${{ matrix.config.cargo_build_flags}}

      - name: Test
        uses: actions-rs/cargo@v1
        continue-on-error: ${{ matrix.config.toolchain == 'nightly' }}
        with:
          command: test
          args: --verbose --all ${{ matrix.cargo_flags }}

  test_no_alloc:
    name: Test no-alloc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/no-alloc
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: build
          args: --verbose --all

  test_no_std:
    name: Test no-std
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/no-std
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: build
          args: --verbose --all
